---
- name: Terminate AWS EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_facts:
        filters:
          "tag:Role": "{{ ec2_tag_Role }}"
        region: "{{ ec2_region }}"
      register: ec2

    - name: display ec2 instances
      run_once: true
      debug:
        var: ec2  

    - name: Remove registered instances
      run_once: true
      ec2:
        state: absent
        wait: true
        instance_ids: "{{ ec2|json_query('instances[*].instance_id') }}"
        region: "{{ ec2_region }}"
      when: ec2